services:
  api:
    build:
      context: api
    container_name: api
    environment:
      PORT: 8000
    ports:
    - '8000:8000'
  front:
    build:
      context: front
    container_name: front
    ports:
    - '3000:3000'
